### ISSUE TITLE
Writing tests for consistent hashing module

### ISSUE THREAD

**Issue by yczeng** [sipb/spike#1]
So far, we have made progress on consistent hashing, connection tracking, and server health checks.
consistent hashing: https://github.com/jma100/spike (jingweim)
server health checks: https://github.com/CatherineZeng/spike (yczeng)
connection tracking: https://github.com/ed1d1a8d/spike/blob/lru-testing/lru-test/lru-test.go (twang6)
We are trying to put together the modules atm.

issues: writing tests for consistent hashing module: (dkogut, gh1)

**Comment by peterg17** [comment]
I want to get Spike development back up and going over the summer. Do you think each person on this could do a pull request on their branch. I think that, going forward, people should create new branches for certain features rather than forking the repo and working on it there, because that makes it hard to get all of the code in one place.
